# Generated by Django 6.0 on 2025-12-12 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_games_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('challenge_type', models.CharField(choices=[('fixed_grid', 'Fixed Grid Challenge'), ('time_limited', 'Time Limited Challenge'), ('word_goal', 'Word Goal Challenge'), ('combined', 'Combined Challenge')], max_length=20)),
                ('grid', models.TextField()),
                ('solutions', models.TextField()),
                ('time_limit', models.IntegerField(blank=True, null=True)),
                ('word_goal', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('words_found', models.IntegerField()),
                ('words', models.TextField()),
                ('time_taken', models.IntegerField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard', to='api.challenge')),
            ],
            options={
                'ordering': ['-score', 'time_taken'],
                'unique_together': {('challenge', 'user_id')},
            },
        ),
    ]
